import { hero_tshirt, hero_sneakers, hero_accessories } from '../assets';
export const STATIC_DATA = {
  ENGLISH: {
    Navbar: {
      SEARCH_PLACEHOLDER: 'Search for products...',
      SIGN_IN_CREATE_ACCOUNT: 'Sign In',
      USER_MENU_ITEMS: [
        { name: 'My Account', path: '/profile' },
        { name: 'My Orders', path: '/order-history' },
        { name: 'Logout', path: '/logout' },
      ],
    },
    UserProfile: {
      USERNAME_PLACEHOLDER: 'Enter your name',
      USEREMAIL_PLACEHOLDER: 'Enter your email',
      USERMOBILE_PLACEHOLDER: 'Enter your mobile',
      AVATAR_ALT_TAG: 'User Profile',
    },
    Footer: {
      FOOTER_CONTACT_INFO_HEADING: 'Contact Info',
      FOOTER_CONTACT_INFO:
        ' Phone : (+91) 134567890 Address : 80A MG Road, Udayan Building, Kolkata West Bengal - 700415, India',
      FOOTER_CATEGORY_HEADING: 'ONLINE SHOPPING',
      FOOTER_SUBSCRIPTION_HEADING: "Let's stay in touch",
      FOOTER_SUBSCRIPTION_INFO:
        'Keep up to date with our latest news and special offer',
    },
    ShoppingCart: {
      SHOPPINGCART_HEADING: 'SHOPPING CART',
      SHOPPINGCART_ITEM_HEADING: 'Item',
      SHOPPINGCART_ITEM_COST: 'Item Cost',
      SHOPPINGCART_PRICE_HEADING: 'Price',
      SHOPPINGCART_SUMMERY_HEADING: 'Summary',
      SHOPPINGCART_ITEM_TAX: 'Tax @12.5%',
      SHOPPINGCART_ITEM_DELIVERY: 'Delivery',
      SHOPPINGCART_ORDER_TOTAL: 'Order Total',
      SHOPPINGCART_CHECKOUT_BUTTON: 'Proceed to Checkout',
      CONTINUE_SHOPPING: 'Continue Shopping',
      LOGIN_MESSAGE: 'You need to Login first to checkout items.',
      LOGIN_BUTTON: 'Please Sign In',
    },
    Login: {
      LOGIN_HEADING: 'Login',
      LOGIN_MOBILE_TEXT: 'Mobile No.',
      LOGIN_MOBILE_PLACEHOLDER: 'Enter the Mobile No.',
      LOGIN_SENDOTP_BUTTON_TEXT: 'Send OTP',
      LOGIN_INFO_TEXT: 'By signin to agree the terms and conditions',
      LOGIN_OTP_TEXT: 'OTP',
      LOGIN_OTP_PLACEHOLDER: 'Enter the OTP',
      LOGIN_BUTTON_TEXT: 'Login',
      LOGIN_NAME_TEXT: 'Name',
      LOGIN_NAME_PLACEHOLDER: 'Enter the Name',
      LOGIN_PROFILE_BUTTON_TEXT: 'Submit',
      LOGIN_SIGN_WITH_TEXT: 'Or sign in with',
      LOGIN_MOBILE_VALIDATION_TEXT: 'Please enter the mobile no.',
      LOGIN_OTP_VALIDATION_TEXT: 'Please enter the OTP',
      LOGIN_NAME_VALIDATION_TEXT: 'Please enter the name',
    },
    DeliveryAddress: {
      DELIVERYADDRESS_HEADING: 'SELECT DELIVERY ADDRESS',
      DELIVERYADDRESS_PAYMENT_BUTTON: 'Proceed to Payment',
      DELIVERYADDRESS_Add: 'Add New Address',
      ADD_DELIVERYADDRESS_HEADING: 'ADD DELIVERY ADDRESS',
      FIRSTNAME_TEXT: 'First Name',
      FIRSTNAME_PLACEHOLDER: 'Enter first name',
      LASTNAME_TEXT: 'Last Name',
      LASTNAME_PLACEHOLDER: 'Enter last name',
      MOBILE_TEXT: 'Mobile Number',
      MOBILE_PLACEHOLDER: 'Enter mobile number',
      ADDRESS_LINE1_TEXT: 'Address Line 1',
      ADDRESS_LINE1_PLACEHOLDER: 'Enter address line 1',
      ADDRESS_LINE2_TEXT: 'Address Line 2',
      ADDRESS_LINE2_PLACEHOLDER: 'Enter address line 2',
      STATE_TEXT: 'State',
      STATE_PLACEHOLDER: 'Select State',
      CITY_TEXT: 'City',
      CITY_PLACEHOLDER: 'Select City',
      PINCODE_TEXT: 'Pin Code',
      PINCODE_PLACEHOLDER: 'Enter pin code',

      FIRSTNAME_VALIDATION_TEXT: 'Please enter first name',
      ADDRESS1_VALIDATION_TEXT: 'Please enter address1',
      STATE_VALIDATION_TEXT: 'Please select state',
      MOBILE_VALIDATION_TEXT: 'Please enter mobile no.',
      MOBILE_VALID_TEXT: 'Please enter valid mobile no.',
      PINCODE_VALIDATION_TEXT: 'Please enter pin code',
      PINCODE_VALID_TEXT: 'Please enter valid pin code',
    },
    OrderHistory: {
      ORDER_HISTORY_HEADING: 'ORDER HISTORY',
      ORDER_QUANTITY: 'Ordered Quantity',
      TOTAL_ORDERED: 'Total Ordered',
      DEVLIVERED_ON: 'Delivers on',
      ORDERED_ON: 'Ordered on',
    },
    App: {
      CATEGORIES: {
        'T-Shirts': 'tshirt',
        Shirts: 'shirt',
        Shoes: 'shoe',
        Trousers: 'trouser',
        'Other Accessories': 'other',
      },
    },
    ProductDetails: {
      CATEGORY_PRODUCT_SIZES: {
        1: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        2: ['7', '8', '9', '10'],
        3: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        4: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        5: [],
      },
    },
    OrderPlaced: {
      SUCCESS: 'Yay! Your order has been placed.',
      ORDER_HISTORY: 'You can check your order history for further details.',
      CONTINUE_SHOPPING: 'Continue Shopping',
    },
    SideMenu: {
      HELLO: 'Hello',
      GUEST: 'Guest',
      LANGUAGE: 'Choose Language',
      USER_MENU_ITEMS: [
        { name: 'My Orders', path: '/order-history' },
        { name: 'My Wishlist', path: '/wishlist' },
        { name: 'My Account', path: '/profile' },
        { name: 'Logout', path: '/logout' },
      ],
    },
    NO_IMAGE_FOUND: 'No Image Found',
    TAX_PERCENTAGE: 12.5,
    DELIVERY_AMOUNT: 40,
    DELIVERY_AMOUNT_LIMIT: 500,
    STAR_RATING: [1, 2, 3, 4, 5],
    HOME: 'Home',
  },
  SPANISH: {
    Navbar: {
      SEARCH_PLACEHOLDER: 'Buscar productos ...',
      SIGN_IN_CREATE_ACCOUNT: 'Iniciar sesión',
      USER_MENU_ITEMS: [
        { name: 'Mi cuenta', path: '/profile' },
        { name: 'Mis pedidos', path: '/order-history' },
        { name: 'Cerrar sesión', path: '/logout' },
      ],
    },
    UserProfile: {
      USERNAME_PLACEHOLDER: 'Ingrese su nombre',
      USEREMAIL_PLACEHOLDER: 'Ingrese su correo electrónico',
      USERMOBILE_PLACEHOLDER: 'Ingresa tu móvil',
      AVATAR_ALT_TAG: 'Perfil de usuario',
    },
    Footer: {
      FOOTER_CONTACT_INFO_HEADING: 'Información de contacto',
      FOOTER_CONTACT_INFO:
        'Teléfono: (+91) 134567890 Dirección: 80A MG Road, Udayan Building, Kolkata West Bengal - 700415, India',
      FOOTER_CATEGORY_HEADING: 'COMPRAS EN LÍNEA',
      FOOTER_SUBSCRIPTION_HEADING: 'Mantengámonos en contacto',
      FOOTER_SUBSCRIPTION_INFO:
        'Manténgase al día con nuestras últimas novedades y ofertas especiales',
    },
    ShoppingCart: {
      SHOPPINGCART_HEADING: 'CARRITO DE COMPRAS',
      SHOPPINGCART_ITEM_HEADING: 'Artículo',
      SHOPPINGCART_ITEM_COST: 'Costo del artículo',
      SHOPPINGCART_PRICE_HEADING: 'Precio',
      SHOPPINGCART_SUMMERY_HEADING: 'Resumen',
      SHOPPINGCART_ITEM_TAX: 'Impuestos al 12,5%',
      SHOPPINGCART_ITEM_DELIVERY: 'Entrega',
      SHOPPINGCART_ORDER_TOTAL: 'Total del pedido',
      SHOPPINGCART_CHECKOUT_BUTTON: 'Proceder al pago',
      CONTINUE_SHOPPING: 'Continuar comprando',
      LOGIN_MESSAGE: 'Primero debe iniciar sesión para pagar los artículos.',
      LOGIN_BUTTON: 'Iniciar sesión',
    },
    Login: {
      LOGIN_HEADING: 'Iniciar sesión',
      LOGIN_MOBILE_TEXT: 'Número de móvil',
      LOGIN_MOBILE_PLACEHOLDER: 'Ingrese el número de teléfono móvil',
      LOGIN_SENDOTP_BUTTON_TEXT: 'Enviar OTP',
      LOGIN_INFO_TEXT:
        'Al iniciar sesión para aceptar los términos y condiciones',
      LOGIN_OTP_TEXT: 'OTP',
      LOGIN_OTP_PLACEHOLDER: 'Ingrese la OTP',
      LOGIN_BUTTON_TEXT: 'Iniciar sesión',
      LOGIN_NAME_TEXT: 'Nombre',
      LOGIN_NAME_PLACEHOLDER: 'Ingrese el nombre',
      LOGIN_PROFILE_BUTTON_TEXT: 'Enviar',
      LOGIN_SIGN_WITH_TEXT: 'O inicie sesión con',
      LOGIN_MOBILE_VALIDATION_TEXT: 'Ingrese el número de teléfono móvil',
      LOGIN_OTP_VALIDATION_TEXT: 'Ingrese la OTP',
      LOGIN_NAME_VALIDATION_TEXT: 'Ingrese el nombre',
    },
    DeliveryAddress: {
      DELIVERYADDRESS_HEADING: 'SELECCIONAR DIRECCIÓN DE ENTREGA',
      DELIVERYADDRESS_PAYMENT_BUTTON: 'Proceder al pago',
      DELIVERYADDRESS_Add: 'Agregar nueva dirección',
      ADD_DELIVERYADDRESS_HEADING: 'AÑADIR DIRECCIÓN DE ENTREGA',
      FIRSTNAME_TEXT: 'Nombre',
      FIRSTNAME_PLACEHOLDER: 'Ingrese el nombre',
      LASTNAME_TEXT: 'Apellido',
      LASTNAME_PLACEHOLDER: 'Ingrese apellido',
      MOBILE_TEXT: 'Número de móvil',
      MOBILE_PLACEHOLDER: 'Ingresar número de teléfono móvil',
      ADDRESS_LINE1_TEXT: 'Línea de dirección 1',
      ADDRESS_LINE1_PLACEHOLDER: 'Ingrese la línea de dirección 1',
      ADDRESS_LINE2_TEXT: 'Línea de dirección 2',
      ADDRESS_LINE2_PLACEHOLDER: 'Ingrese la línea de dirección 2',
      STATE_TEXT: 'Estado',
      STATE_PLACEHOLDER: 'Seleccionar estado',
      CITY_TEXT: 'Ciudad',
      CITY_PLACEHOLDER: 'Seleccionar ciudad',
      PINCODE_TEXT: 'Código PIN',
      PINCODE_PLACEHOLDER: 'Ingresar código PIN',

      FIRSTNAME_VALIDATION_TEXT: 'Ingrese el nombre',
      ADDRESS1_VALIDATION_TEXT: 'Ingrese la dirección1',
      STATE_VALIDATION_TEXT: 'Seleccione el estado',
      MOBILE_VALIDATION_TEXT: 'Ingresa el número de teléfono móvil',
      MOBILE_VALID_TEXT: 'Ingresa un número de teléfono válido',
      PINCODE_VALIDATION_TEXT: 'Ingrese el código PIN',
      PINCODE_VALID_TEXT: 'Ingrese un código PIN válido',
    },
    OrderHistory: {
      ORDER_HISTORY_HEADING: 'HISTORIAL DE PEDIDOS',
      ORDER_QUANTITY: 'Cantidad pedida',
      TOTAL_ORDERED: 'Total pedidos',
      DEVLIVERED_ON: 'Entrega el',
      ORDERED_ON: 'Pedido el',
    },
    App: {
      CATEGORIES: {
        Camisetas: 'camiseta',
        Camisas: 'camisa',
        Zapatos: 'zapato',
        Pantalones: 'pantalón',
        'Otros accesorios': 'otros',
      },
    },
    ProductDetails: {
      CATEGORY_PRODUCT_SIZES: {
        1: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        2: ['7', '8', '9', '10'],
        3: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        4: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        5: [],
      },
    },
    OrderPlaced: {
      SUCCESS: 'Yay! Su orden ha sido puesta.',
      ORDER_HISTORY:
        'Puede consultar su historial de pedidos para obtener más detalles.',
      CONTINUE_SHOPPING: 'Continuar comprando',
    },
    SideMenu: {
      HELLO: 'hola',
      GUEST: 'Invitado',
      USER_MENU_ITEMS: [
        { name: 'Mis pedidos', path: '/order-history' },
        { name: 'Mi cuenta', path: '/profile' },
        { name: 'Cerrar sesión', path: '/logout' },
      ],
    },
    NO_IMAGE_FOUND: 'No se encontró ninguna imagen',
    TAX_PERCENTAGE: 12.5,
    DELIVERY_AMOUNT: 40,
    DELIVERY_AMOUNT_LIMIT: 500,
    STAR_RATING: [1, 2, 3, 4, 5],
    HOME: 'Hogar',
  },
};

export const SessionKeys = {
  USERNAME: 'username',
};

export const TEST_DATA = {
  CATEGORIES_DATA: [
    { id: 1, name: 'T-Shirts' },
    { id: 2, name: 'Shoes' },
    { id: 3, name: 'Shirts' },
    { id: 4, name: 'Trousers' },
    { id: 5, name: 'Other Accessories' },
  ],
  DELIVERY_ADDRESS_DATA: [
    {
      id: 1,
      name: 'Pitam Saha',
      address: '78 MG ROAD, KOLKATA - 722056',
      isDefault: true,
    },
    {
      id: 2,
      name: 'Sa Saha',
      address: '78 MG ROAD, Mumbai - 400021',
      isDefault: false,
    },
  ],
  STATE_DATA: [
    { id: 1, name: 'Assam' },
    { id: 2, name: 'Andrapadesh' },
    { id: 3, name: 'Bihar' },
    { id: 4, name: 'Delhi' },
    { id: 5, name: 'Gujrat' },
  ],
  CITY_DATA: [
    { id: 1, stateId: 1, name: 'Dibrugarh' },
    { id: 2, stateId: 1, name: 'Jorhat' },
    { id: 3, stateId: 1, name: 'Guwahati' },
    { id: 4, stateId: 1, name: 'Silchar' },
    { id: 5, stateId: 1, name: 'Tezpur' },
    { id: 6, stateId: 2, name: 'Amaravati' },
    { id: 7, stateId: 2, name: 'Guntur' },
    { id: 8, stateId: 2, name: 'Tirupatu' },
    { id: 9, stateId: 2, name: 'Vijaywada' },
    { id: 10, stateId: 2, name: 'Vishakhapatnam' },
    { id: 11, stateId: 3, name: 'Gaya' },
    { id: 12, stateId: 3, name: 'Munger' },
    { id: 13, stateId: 3, name: 'Muzaffapur' },
    { id: 14, stateId: 3, name: 'Nalanda' },
    { id: 15, stateId: 3, name: 'Patna' },
    { id: 16, stateId: 4, name: 'Gaziabad' },
    { id: 17, stateId: 4, name: 'Gurugram' },
    { id: 18, stateId: 4, name: 'Faridabad' },
    { id: 19, stateId: 4, name: 'New Delhi' },
    { id: 20, stateId: 4, name: 'Sonipat' },
    { id: 21, stateId: 5, name: 'Ahamedabad' },
    { id: 22, stateId: 5, name: 'Gandhinagar' },
    { id: 23, stateId: 5, name: 'Rajkot' },
    { id: 24, stateId: 5, name: 'Surat' },
    { id: 25, stateId: 5, name: 'Vadodara' },
  ],
  HERO_DATA: [
    {
      id: 1,
      category: 'T-Shirts',
      categoryId: 1,
      photo: hero_tshirt,
      text: 'New Arrivals',
    },
    {
      id: 2,
      category: 'Shoes',
      categoryId: 2,
      photo: hero_sneakers,
      text: 'Shoes',
    },
    {
      id: 3,
      category: 'Shirts',
      categoryId: 3,
      photo: hero_accessories,
      text: 'Collections',
    },
  ],
  ORDER_HISTORY_DATA: [
    {
      id: 1,
      productname: 'Printed Polo Collar T-shirt',
      category: 'T-Shirts',
      categoryId: 1,
      productId: 2,
      total_price: 531,
      quantity: 1,
      order_date: '12-Apr-2021',
      delivery_date: '17-Apr-2021',
      image:
        'https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/2521204/2018/2/26/11519626464547-na-8991519626464330-1.jpg',
    },
    {
      id: 2,
      productname: 'Women Analogue Watch',
      category: 'Other Accessories',
      categoryId: 5,
      productId: 41,
      total_price: 319,
      quantity: 1,
      order_date: '1-Mar-2021',
      delivery_date: '9-Mar-2021',
      image:
        'https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/2211587/2018/5/28/7d6edb63-8219-4d33-b02a-7d860a4d11711527489620300-DressBerry-Women-Brown-Analogue-Watch-8741527489620072-1.jpg',
    },
  ],
};
